# Generated by Django 3.0.7 on 2020-12-15 20:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Economics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('RUB', 'Rubel'), ('USD', 'Dollar')], default='RUB', max_length=3)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='AccountAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat', models.BooleanField(default=False)),
                ('revs_tax', models.BooleanField(default=False)),
                ('revenue_tax', models.BooleanField(default=False)),
                ('money', models.BooleanField(default=False)),
                ('money_change', models.FloatField()),
                ('vat_value', models.FloatField()),
                ('tax_value', models.FloatField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='operations', to='Economics.CurrencyState')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='operations', to='Economics.Operation')),
            ],
        ),
    ]
